# Generated by Django 5.2.7 on 2025-10-26 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Recursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_recurso', models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('zip', 'ZIP')], max_length=50)),
                ('recurso', models.FileField(upload_to='recursos/')),
                ('acesso_previo', models.BooleanField(default=False)),
                ('draft', models.BooleanField(default=True)),
                ('nome_recurso', models.CharField(max_length=255)),
                ('descricao_recurso', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Treinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('link_acesso', models.URLField()),
            ],
        ),
    ]
