# Generated by Django 5.2.7 on 2025-10-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0002_initial'),
        ('users', '0002_alter_aluno_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='alunos',
            field=models.ManyToManyField(related_name='turmas', to='users.aluno'),
        ),
    ]
