# Generated by Django 5.2.7 on 2025-10-29 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0003_turma_alunos'),
        ('users', '0002_alter_aluno_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='alunos',
            field=models.ManyToManyField(blank=True, null=True, related_name='turmas', to='users.aluno'),
        ),
    ]
