# Generated by Django 5.2.7 on 2025-10-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0004_alter_turma_alunos'),
        ('users', '0002_alter_aluno_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recursos',
            name='turma',
        ),
        migrations.AddField(
            model_name='turma',
            name='recursos',
            field=models.ManyToManyField(related_name='turmas', to='treinamento.recursos'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='alunos',
            field=models.ManyToManyField(related_name='turmas', to='users.aluno'),
        ),
    ]
