# Generated by Django 5.2.7 on 2025-10-31 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0005_remove_recursos_turma_turma_recursos_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together={('treinamento', 'nome')},
        ),
        migrations.AddField(
            model_name='recursos',
            name='turma',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurso', to='treinamento.turma'),
        ),
        migrations.AlterField(
            model_name='treinamento',
            name='nome',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='recursos',
            unique_together={('tipo_recurso', 'nome_recurso')},
        ),
        migrations.RemoveField(
            model_name='turma',
            name='alunos',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='recursos',
        ),
    ]
